package org.team2642.robot.subsystems;

import org.team2642.robot.PIDSpeedController;
import org.team2642.robot.RobotMap;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Lift extends Subsystem {
	
    Talon lift = RobotMap.liftMotor;
    DigitalInput topLimit = RobotMap.topLimit;
    DigitalInput bottomLimit = RobotMap.bottomLimit;
    DigitalInput recieve = RobotMap.toteInRobot;
    DigitalInput lot = RobotMap.lotOfTotes;
    Encoder liftEncoder = RobotMap.liftEncoder;
    Compressor compressor = RobotMap.compressor;
    Solenoid dogs = RobotMap.dogs;
    Solenoid pusher = RobotMap.pusher;
    Solenoid flipper = RobotMap.flipper;
    PIDSpeedController pid = new PIDSpeedController(liftEncoder, lift, "Lift", "Speed Control");
    
    public String subsystemName;
    
    public final double liftUpperBound = 1150;
    public final double liftLowerBound = 80;
    
    /*
    public static DigitalInput topLimit;
    public static DigitalInput bottomLimit;
    public static DigitalInput toteInRobot;
    public static DigitalInput lotOfTotes;
    public static Encoder liftEncoder;
    public static Encoder backLiftEncoder;
    public static Encoder frontLiftEncoder;
	 */

    public Lift(String subsystem) {
    	subsystemName = subsystem;
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        //setDefaultCommand(new LiftOverride());
    }
    
    public void setPIDConstants() {
		double p = Preferences.getInstance().getDouble("LiftSpeedP", 0);
		double i = Preferences.getInstance().getDouble("LiftSpeedI", 0);
		double d = Preferences.getInstance().getDouble("LiftSpeedD", 0);
		double f = Preferences.getInstance().getDouble("LiftSpeedF", 0);

		pid.setConstants(p, i, d, f);

		liftEncoder.setDistancePerPulse(Preferences.getInstance().getDouble(
				subsystemName + "LiftDistPerPulse", 1));
	}
    
    private double getLiftSpeed() {
    	return Math.max(Preferences.getInstance().getDouble("LiftSpeed", 0), 0);
	}
    
    public void moveLiftUp() {
		//movementState = LiftMovement.Up;
		//releaseBrake();
		if (!getTopLimit() || liftEncoder.getDistance() < liftUpperBound) {
			pid.set(-getLiftSpeed());
		}
		SmartDashboard.putString(subsystemName + "Move state", "Up");
		SmartDashboard.putNumber(subsystemName, liftEncoder.getRate());
	}

	public boolean isLiftAboveDogs() {
		return (liftEncoder.getDistance() > 1200);
	}
    
    public void moveLiftDown() {
		//movementState = LiftMovement.Down;
		//releaseBrake();
		if (liftEncoder.getDistance() > liftLowerBound) {
    		pid.set(getLiftSpeed());
		}
		SmartDashboard.putString(subsystemName + "Move state", "Down");
		SmartDashboard.putNumber(subsystemName, liftEncoder.getRate());
	}

	public void stopLift() {
		//movementState = LiftMovement.Stopped;
		pid.set(0);
		//setBrake();
		SmartDashboard.putString(subsystemName + "Move state", "Stop");
	}
	
    public double getLiftEncoderDist() {
    	return liftEncoder.getDistance();
    }
    public double getLiftEncoderRate() {
    	return liftEncoder.getRate();
    }
    
    public void resetLiftEncoder() {
    	liftEncoder.reset();
    }
    
    public boolean getToteInRobot() {
    	return recieve.get();
    }
    
    public boolean getTopLimit() {
    	return topLimit.get();
    }
    
    public boolean getBottomLimit() {
    	return bottomLimit.get();
    }
    
    public boolean getFiveIn() {
    	return lot.get();
    }
    
    public void moveLiftToPos(double position) {
    	double tolerance = 10;
    	if (liftEncoder.getDistance() > position + tolerance) {
    		pid.set(getLiftSpeed());
    	} else if (liftEncoder.getDistance() < position - tolerance) {
    		pid.set(-getLiftSpeed());
    	}
    }
    
    public boolean liftAtTarget(double position) {
    	double tolerance = Preferences.getInstance().getDouble("Lift Tolerance", 10);
    	return (liftEncoder.getDistance() < position + tolerance && liftEncoder.getDistance() > position - tolerance);
    }
    
    public boolean getDogs() {
    	return dogs.get();
    }
    public void setDogs(boolean on) {
    	dogs.set(on);
    }
    public void setPusher(boolean on) {
    	pusher.set(on);
    }
    public void setFlipper(boolean on) {
    	flipper.set(on);
    }
    
    public void startCompressor() {
    	compressor.start();
    }
    public void stopCompressor() {
    	compressor.stop();
    }
    
    
    
}

